### ISSUE TITLE
Setup README 

### ISSUE THREAD

**Issue by si** [Mermade/rss2twitter#1]
It would be great if there was a simple setup in the README, especially as someone relatively inexperienced with using Node and setting up new apps.

I can see some dependent packages in the packages.json and index.js so is it just a case of cloning and running `npm install`? Is it straight forward to roll up on a Linode instance?

**Comment by MikeRalphson** [comment]
@si How's that?

**Comment by si** [comment]
OooOOoooh! Looks great. I'll give it a go and let you know (maybe raise a pull request for any suggestions).

**Comment by MikeRalphson** [comment]
Cool. If I can work out which key/secret is app specific and not account specific, I can send you those values to save you having to register your own app.

**Comment by si** [comment]
OK, so I've:

1. Clone the repo to a Linode
2. Install Node on the Linode along with other suitable dependencies
3. Run `npm -i` to install dependent Node packages.
4. Register for a Twitter Developer account following recent changes to the API policy
5. Now waiting for approval…

Hopefully it'll go through. Slightly concerned that my feed is reusing content from another official source without consent. It could be a blocker so let's see.

**Comment by MikeRalphson** [comment]
I've added the node.js install/support info to the `README.md` file.

**Comment by si** [comment]
**Good news!** First run (with sudo permissions) was relatively successful:

```bash
sijobling@localhost:/var/www/html/rss2twitter$ sudo node index.js http://bbc-rss.herokuapp.com/cache/radio/available/genre/C00193.rss
Articles: 0
```

Now I just need to configure a `crontab` and keep an eye on it.

**Comment by MikeRalphson** [comment]
Yay!

**Comment by MikeRalphson** [comment]
Will have a look.

**Comment by si** [comment]
Looks like some data's coming back now but I've got Twitter authentication issues:
```
sijobling@localhost:~$ sudo node /var/www/html/rss2twitter/index.js http://bbc-rss.herokuapp.com/cache/radio/available/genre/C00193.rss
[sudo] password for sijobling:
Articles: 323
http://bbc.co.uk/programmes/b007jl9j
The Goon Show The Whistling Spy Enigma #comedy - Spy Neddie must make contact with his informer. But can he whistle the secret tune? Stars Spike Milligan. From September 1954.
http://bbc.co.uk/programmes/b07m5dz0
The Infinite Monkey Cage: Series 14 (Episode 5) 200 Years of Frankenstein #comedy - Brian Cox and Robin Ince celebrate the 200th anniversary of Mary Shelley's Frankenstein.
http://bbc.co.uk/programmes/b0bnkhbs
The Comedy Club Interviews Angela Barnes 2/2 #comedy - Arthur Smith chats again to Angela Barnes about comedian Linda Smith.
http://bbc.co.uk/programmes/m0000nm5
Josh Howie's Losing It: Series 2 The Choice #comedy - Second series of the sitcom starring stand-up comic Josh Howie, coming to terms with the birth of his first child.
http://bbc.co.uk/programmes/p05w5bkx
The Boring Talks Boring Talks #01 - The End Of The World #comedy - What is the specific date of Armageddon according to Douglas Adams? Steve Cross close-reads The Hitchhiker's Guide To The Galaxy to find out
{ Error: Invalid or expired token.
    at Object.exports.makeTwitError (/var/www/html/rss2twitter/node_modules/twit/lib/helpers.js:74:13)
    at onRequestComplete (/var/www/html/rss2twitter/node_modules/twit/lib/twitter.js:344:25)
    at Request.<anonymous> (/var/www/html/rss2twitter/node_modules/twit/lib/twitter.js:364:7)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (/var/www/html/rss2twitter/node_modules/request/request.js:1083:12)
    at Gunzip.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  message: 'Invalid or expired token.',
  code: 89,
  allErrors: [ { code: 89, message: 'Invalid or expired token.' } ],
  twitterReply: { errors: [ [Object] ] },
  statusCode: 401 }
{ Error: Invalid or expired token.
    at Object.exports.makeTwitError (/var/www/html/rss2twitter/node_modules/twit/lib/helpers.js:74:13)
    at onRequestComplete (/var/www/html/rss2twitter/node_modules/twit/lib/twitter.js:344:25)
    at Request.<anonymous> (/var/www/html/rss2twitter/node_modules/twit/lib/twitter.js:364:7)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (/var/www/html/rss2twitter/node_modules/request/request.js:1083:12)
    at Gunzip.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  message: 'Invalid or expired token.',
  code: 89,
  allErrors: [ { code: 89, message: 'Invalid or expired token.' } ],
  twitterReply: { errors: [ [Object] ] },
  statusCode: 401 }
{ Error: Invalid or expired token.
    at Object.exports.makeTwitError (/var/www/html/rss2twitter/node_modules/twit/lib/helpers.js:74:13)
    at onRequestComplete (/var/www/html/rss2twitter/node_modules/twit/lib/twitter.js:344:25)
    at Request.<anonymous> (/var/www/html/rss2twitter/node_modules/twit/lib/twitter.js:364:7)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (/var/www/html/rss2twitter/node_modules/request/request.js:1083:12)
    at Gunzip.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  message: 'Invalid or expired token.',
  code: 89,
  allErrors: [ { code: 89, message: 'Invalid or expired token.' } ],
  twitterReply: { errors: [ [Object] ] },
  statusCode: 401 }
{ Error: Invalid or expired token.
    at Object.exports.makeTwitError (/var/www/html/rss2twitter/node_modules/twit/lib/helpers.js:74:13)
    at onRequestComplete (/var/www/html/rss2twitter/node_modules/twit/lib/twitter.js:344:25)
    at Request.<anonymous> (/var/www/html/rss2twitter/node_modules/twit/lib/twitter.js:364:7)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (/var/www/html/rss2twitter/node_modules/request/request.js:1083:12)
    at Gunzip.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  message: 'Invalid or expired token.',
  code: 89,
  allErrors: [ { code: 89, message: 'Invalid or expired token.' } ],
  twitterReply: { errors: [ [Object] ] },
  statusCode: 401 }
{ Error: Invalid or expired token.
    at Object.exports.makeTwitError (/var/www/html/rss2twitter/node_modules/twit/lib/helpers.js:74:13)
    at onRequestComplete (/var/www/html/rss2twitter/node_modules/twit/lib/twitter.js:344:25)
    at Request.<anonymous> (/var/www/html/rss2twitter/node_modules/twit/lib/twitter.js:364:7)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (/var/www/html/rss2twitter/node_modules/request/request.js:1083:12)
    at Gunzip.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  message: 'Invalid or expired token.',
  code: 89,
  allErrors: [ { code: 89, message: 'Invalid or expired token.' } ],
  twitterReply: { errors: [ [Object] ] },
  statusCode: 401 }
Calling finalize...
```
I'm away this weekend but will have a look when I'm back. Might just re-enable the dlvr.it account for now, even if it's just limited to 3 posts a day.

**Comment by si** [comment]
I've (finally) got around to looking at this and I'm no longer getting the errors but I'm also getting no `Articles:` output.

Is there any way to log the output to understand what's happening under the hood?

**Comment by MikeRalphson** [comment]
Just ping me any time on Slack you're free to check into this.

**Comment by MikeRalphson** [comment]
Chase if you need anything else.
